- name: get local python packages
  hosts: all
  gather_facts: false
  tasks:
  - name: get local python packages
    set_fact:
        local_py_zun: http://10.10.131.3/images/tianni/zun-4.0.2.dev1-py2-none-any.whl
        local_py_zunclient: http://10.10.131.3/images/tianni/python_zunclient-3.6.1.dev1-py2-none-any.whl
        local_py_zun_ui: http://10.10.131.3/images/tianni/zun_ui-4.0.1.dev1-py2-none-any.whl

- name: update python package(s) in {{ container_name }}
  hosts: zun-compute
  gather_facts: false
  vars:
    container_name: zun_compute
    container_user: root
    update_package: 
      - "{{ local_py_zun }}"
  tasks:
  - name: update {{ update_package }}
    shell: |
      docker exec -u {{ container_user }} -it {{ container_name }} pip install {{ update_package | join(' ') }}
  - name: restart {{ container_name }} container
    shell: |
      docker restart {{ container_name }}

- name: update python package(s) in {{ container_name }}
  hosts: control
  gather_facts: false
  vars:
    container_name: kolla_toolbox
    container_user: ansible
    update_package: 
      - "{{ local_py_zunclient }}"
  tasks:
  - name: update {{ update_package }}
    shell: |
      docker exec -u {{ container_user }} -it {{ container_name }} pip install {{ update_package | join(' ') }}
  - name: restart {{ container_name }} container
    shell: |
      docker restart {{ container_name }}

- name: update python package(s) in {{ container_name }}
  hosts: horizon
  gather_facts: false
  vars:
    container_name: horizon
    container_user: root
    update_package: 
      - "{{ local_py_zunclient }}"
      - "{{ local_py_zun_ui }}"
  tasks:
  - name: update {{ update_package }}
    shell: |
      docker exec -u {{ container_user }} -it {{ container_name }} pip install {{ update_package | join(' ') }}
  - name: restart {{ container_name }} container
    shell: |
      docker restart {{ container_name }}

