- name: get local python packages
  hosts: all
  gather_facts: false
  tasks:
  - name: get local python packages
    set_fact:
        py_zun: "{{ zun_dist }}"
        py_zunclient: "{{ zunclient_dist }}"
        py_zun_ui: "{{ zun_ui_dist }}"

- name: update python package(s) in {{ container_name }}
  hosts: zun-compute
  gather_facts: false
  vars:
    container_name: zun_compute
    container_user: root
    update_package: 
      - "{{ py_zun }}"
  tasks:
  - name: update {{ update_package }}
    shell: |
      docker exec -u {{ container_user }} -it {{ container_name }} pip install {{ update_package | join(' ') }}
    when: enable_zun == "yes"
  - name: restart {{ container_name }} container
    shell: |
      docker restart {{ container_name }}
    when: enable_zun == "yes"

- name: update python package(s) in {{ container_name }}
  hosts: control
  gather_facts: false
  vars:
    container_name: kolla_toolbox
    container_user: ansible
    update_package: 
      - "{{ py_zunclient }}"
  tasks:
  - name: update {{ update_package }}
    shell: |
      docker exec -u {{ container_user }} -it {{ container_name }} pip install {{ update_package | join(' ') }}
    when: enable_zun == "yes"
  - name: restart {{ container_name }} container
    shell: |
      docker restart {{ container_name }}
    when: enable_zun == "yes"

- name: update python package(s) in {{ container_name }}
  hosts: horizon
  gather_facts: false
  vars:
    container_name: horizon
    container_user: root
    update_package: 
      - "{{ py_zunclient }}"
      - "{{ py_zun_ui }}"
  tasks:
  - name: update {{ update_package }}
    shell: |
      docker exec -u {{ container_user }} -it {{ container_name }} pip install {{ update_package | join(' ') }}
    when: enable_zun == "yes"
  - name: restart {{ container_name }} container
    shell: |
      docker restart {{ container_name }}
    when: enable_zun == "yes"

