#!/bin/bash

has_tianni() {
    # mount can failed silently
    [[ -z "$TIANNI_SRC" || -z "$TIANNI_DIR" ]] || mount $TIANNI_SRC $TIANNI_DIR &>/dev/null
    cat ${TIANNI_DIR}/VERSION |grep "^TianNi" &>/dev/null
}

install_kolla() {
    local upgrade=(pip setuptools)
    local install=(docker ansible kolla-ansible tox)

    has_tianni
    if [ $? -eq 0 ]; then
        pip install --upgrade --no-index --find-links ${TIANNI_DIR}/pip/ ${upgrade[@]}
        pip install --no-index --find-links ${TIANNI_DIR}/pip/ ${install[@]}
    else
        pip install --upgrade ${upgrade[@]}
        pip install ${install[@]}
    fi

    mkdir -p /etc/ansible
    cat > /etc/ansible/ansible.cfg << eof1
[defaults]
pipelining=True
forks=100
deprecation_warnings=False
eof1
}

config_kolla() {
    mkdir -p $ETCKOLLA
    cp -r ${KOLLADIR}/etc_examples/kolla/* $ETCKOLLA
    cp ${KOLLADIR}/ansible/inventory/* $ETCKOLLA
}

ansible_ping_hosts() {
    ansible -i $ETCKOLLA/$INVENTORY all -m ping
}

# test and skip if defined
[ -z "$KOLLADIR" ] && . tn-openstack-var

# check on host
type pip || { echo "pip not found" >&1; exit 1; }
type easy_install || { echo "please install python setuptools" >&1; exit 1; }

# copy files to work dir, then activate venv
set -o xtrace
mkdir -p $WORKDIR
cp globals.yml $INVENTORY passwords.yml $WORKDIR
cd $WORKDIR
virtualenv $VENVDIR || exit -1
source ${VENVDIR}/bin/activate
set +o xtrace

# install kolla in venv
install_kolla || exit -2

# copy kolla config
config_kolla || exit -3

# XXX: kolla-genpwd
cp globals.yml $INVENTORY passwords.yml $ETCKOLLA

ansible_ping_hosts || exit -4
